### ISSUE TITLE
Fails on (some) valid input data

### ISSUE THREAD

**Issue by Phelimb** [kvarq/kvarq#1] opened 2014-10-16 16:01 UTC
KvarQ failed to scan some vaild fastqs 

[2014-10-16 14:14:57,638] -INFO- cli.py:477(main) :: loaded testsuite "example" from "/home/phelimb/tools/kvarq-master/testsuites/MTBC/example.py"
[2014-10-16 14:14:57,655] -INFO- cli.py:477(main) :: loaded testsuite "phylo" from "/home/phelimb/tools/kvarq-master/testsuites/MTBC/phylo.py"
[2014-10-16 14:14:57,666] -INFO- cli.py:477(main) :: loaded testsuite "resistance" from "/home/phelimb/tools/kvarq-master/testsuites/MTBC/resistance.py"
[2014-10-16 14:14:57,671] -INFO- cli.py:477(main) :: loaded testsuite "spoligo" from "/home/phelimb/tools/kvarq-master/testsuites/MTBC/spoligo.py"
[2014-10-16 14:14:57,916] -INFO- fastq.py:146(**init**) :: gzipped fastq : readlength=? records_approx=? dQ=0 variants=['Sanger']
[2014-10-16 14:14:57,917] -INFO- cli.py:86(scan) :: scanning 
[===================== 99% ====================>] 1m 0s / 1m 2s   [2014-10-16 14:15:57,981] -ERROR- cli.py:161(scan) :: could not scan 
file : record must start with '@' (and not 'F') fpos=984389052 [cli.py:101 -> /python2.7/site-packages/kvarq-0.12.2-py2.7-linux-x86_64.egg/kvarq/analyse.py:322]

grep '^F' fastq_file returns nothing so it doesn't look like there's any line in the file that starts with an F. 

fpos=984389052 is out of 984389772 total bytes. so 99.9999% of the way through the file. 

I've manually checked the fastq and the last record looks fine. I've also fully parsed the file with BioPython and with another fq parser without error. 

The last record looks like this. 
!!!!CDCF8:DCDGGDFEGF-EDHGH?GGFDHEFBEDIAFBFEGFDGEEGGG7GHEFHGFE.EDECE8FGFDG@GFBHCFCFFCFDGF=GC,FE+>E@DF
@HS22_09330:8:2316:21315:56524#77
NNNNTCCCTTTTCTCAACATTGCCGAAGACCACCTGTATGGGGAGGCAACGATGGCCGAATCAACCGGGCCCAAGCCCCGGGGGCGGCCCGCGGGGGGGG
+
!!!!7?-?(-,?EA?6BF?F9EE68,,DCBB9FB7?,,,,C,''+-D''78-7D>D+,8''(.-E#7-6'C,,-7,7,'E66',7,,557C,6,HFE'&4

This issue does not appear on every sample, only a few files.

**Comment by kvarq** [comment] 2014-10-16 16:12
hi Phelim

can you paste the last 10kb of the file? this should then include the fpos=984389772-720=984389052 and I'll try to figure out where it finds the offending "F"...

best, Andreas

**Comment by Phelimb** [comment] 2014-10-16 16:15
@HS22_09330:8:2316:21243:9186#77
AGGCCCTCGAACCCTACTTCGACGAAATGTTCCTCGGCCGTGGCGATGTCACGACAACCCTGAGGCAGGCACAGGCGGCGGCCAATGCTGCCACACAGCG
+
9B@DEDDFFDDDEEBDGEFFGE@HDDCGEBHF6FCEAEFEBEJEBEEDFGGD7DEBEHGEEDEGEGEGFBD5CEA7FEBFCFE,AC,<A7CC67E><D,?
@HS22_09330:8:2316:21243:42934#77
GTGCTCGACCGGATCCGGACTCATGTGTTCGGCACAGGACGGAGGCCCCGCGGGTGCTCTGTCGCTATGCGTGTGGCGCAGTGGCCGCGGGTACTAGCTA
+
0A=DEDFFEDF?8D?>E??BBBA6EEFCE?BBE+F-EIFE?F=EC-DE7,CEHD-E6E88>:EDF@,-@ADAB8?7@A67EF5ED87=DC,6A7<,>-=E
@HS22_09330:8:2316:21244:54770#77
GCCCGGTGTCCGGCGCCCCGTTGGCACCGTTGCCGATCAGTGGGCGCCCCAACAGCGCCTGGGCGGGGGCGTTGACCGCGGCCAGCATGTTCGGCCCGGC
+
9ABDEDDFDGDDGGDFFDE9GIEEDH7LE?J-EFF?DEAED?FGBBG=E7GGHGE9DHGFEFBGEGDGFGFDBGEE7EFFEFFBFCDFDGHFG74BC-BE
@HS22_09330:8:2316:21247:27698#77
CGGCAACGGGTGGCGATGGGTCGTGCGATCGTGCGGCGCCCACAGGTATTCCTGATGGACGAACCGCTGTCCAATCTTGACGCCAAACTTCGCGGGCAAA
+
8ABDE:DAECDHAGA>?EGF9FDEDHFACFD-F>>EAB,ED?FGCDEDEDCHD@BB+>8FE:BCFGEG@BF58HF,GHD7EF;CF??FF?,?=E4F6C7+
@HS22_09330:8:2316:21250:9337#77
CGCTTGCCCGCGCCGCCGATCAGGGAATGCAGGTTGAAATCTTGCCCGCACCGACCAGGCTATTCCCGCCATCGCTCGCCGTTGTGTTCTCCCGTTCGAG
+
9A=CBD:D@EDD8GD6E8BAB,ADEEC,86D9D5FBDADBDGEGFA:DFGG?HDE->C8,E(;-8@C=FA?ACBAED7BFC6A7ECDFDCD,DICCE-@?
@HS22_09330:8:2316:21258:23815#77
ATCTTCGGGTTCAGCTTCTACACCGGCCACTATTTTGGGGCTTGGGTCTTCATTGCGGGTTTCCTGTTGCATATCGTGGTCAAGATCCCCCACATGGTCA
+
7AACC:C6D>FCDBADFFGFGBDE8BFDFFD>EEBBE?7E?FG7BB:6BG@?HFC9DDEEBDBD?BCG6DFD8BA7@HC>CBD>7E7+F?HEG?HFC7@E
@HS22_09330:8:2316:21259:62912#77
GCCCCCGGCCCGGGGGCTGTGCCGCCGCTAGTGTCTGGTCCGCTGCGTGCCATGGGGTCGTTCCTCTCGGCTTGGCTCATGAGGTCGTCCGAACGCTAAT
+
9AA-BDDFFGFHGDGFIIGFDFAHGBFGEBHF6DEBEFE7H7BEIGDDEGDEEDHBEEG8EDEDEEEG6DDDG8E7DEBE>,ACA8?5A?C?=?CB@7DE
@HS22_09330:8:2316:21264:52779#77
GTCTCGGCGCGCCTCATGTCCTCCTCGGGCGAATGCTATCGCCGCGAGAAGTCATGAGAAACGGGTTCCCCCGAGAAGCGCGTTCGAGCTAGGCGAGCGC
+
9-B:,DA6F>DCAG'+BDE9(E66D?FCEBB-BD>7I8A,D?,G@D%BC,CD?D8D+EG?9FEAD,?-CAF>8@F7@??>GC5B>8'A577?D7<6,D7F
@HS22_09330:8:2316:21265:42193#77
GACATGCCCGCCGACAGACCGATCGCGTGCGGGAACATCGCACGCACCCGGTTGTGCTCCGATTGCAGCCGGTCAAAGGCCTCGTCCGGGTCCCAATCCA
+
9BBABDDAEGCLEBGDGIGFDFGH8HD,EFDEGDBEBIABFEE7IHED7?ECDDEFH7GEE:EGE,HGFECEC8?E@7CFDFCEEBCFAD7FFDH,EDG4
@HS22_09330:8:2316:21266:41155#77
AGCGTTGATCGAGCAGTACCACGCTTACACGCCGCGGGATCTCGTCGACCACCCCGGCCCGCCTCATGTGCAAGGCGCGTTCACCATAGGCGAGAACAGC
+
9A7:CDAAG>D?EDGF?FB-97E,?E,A,GDH=F7E'?77?GGE5E:6C=E?ED>F>AGCGCECFGEBFGF>?CE7GEGEEFA7EE??+-E'6HD,=@D<
@HS22_09330:8:2316:21266:64124#77
CGAAAACCCTTTGATCAATGATCCATTCGCCGAGCCGCTGGTGCGCCGCGGCGGCATCGGCCTGTTTACCCGGCGGGCCAGCGGCGAGTTGAGGCTTGAG
+
0B=-@(DF,:DC8BB>EFEDBIE,'EC',6?9,5C?AE7FB,EBC-(+BG-9?98B6A@'9A;C?8?DCAB>B8,?B7BF>F5CF8'5+7>'=74B6''<
@HS22_09330:8:2316:21271:12901#77
GTCCAGGGACGGCACCGTCGGCGCAAGCAGACCCGCAAGCGCGACCCAGAAGGCGATCACCACCCACGGCCTTCGGACGATAAGGCGCCCTAGCCGCGGA
+
9AB-@D:BDGDDAEG>I8DDG@EDEEFC8FBH6DCEBEE>C7BEBE.6BD@C79>9DHGF9ABDF8HB@EDDC8F77H?F>FF7FC7FF?C6AE4>ED=F
@HS22_09330:8:2316:21272:40454#77
ATCCGCGTCGCGGTTCCGGCGGTGCTGGTGCTGGACCCGTTCTGGCTGATCCCGACGTTGCTGGACGTCCACTTGAGCATGACGTTACAGCACGTGGACA
+
0BACFDDB,D8?EDD>,,BBBB@6DB,88BD9EB'7AB7CDABE59DD77D'?D?FEEGD>B.BEC?BFBFDG87,7B?EG6E77,,F+CC6E?<B<C=C
@HS22_09330:8:2316:21272:87499#77
GACTTGGACGACAAGGAAGCCCTCGCCGAACTGATCGGCGACAATGCTGCTCCTTGACGTAAGCGTCTGCATATTCGCCATCCGCGAGGACAGCTGCCCC
+
9AACE:DADEFCEDDEFF6FGBECGDFGEGDFBDFBI8,FB7GG@EDDBDGDH@E@6EGF>ADDDCEDFD7DCCE?DH6FEF57EBDFD7>BEEGFEG=4
@HS22_09330:8:2316:21273:81618#77
CTGTGGATAAAGCTGTGGAAACTGTGGATAGTCGTAGGTAGCTGTGTCGTGCTGGACGTGCCGCGACCGGGCGCGCCCAATCCAGCGCGGAAGCCTGCCT
+
9@BACD:DDG>L@ED+68DA97EC8H?8C6?H,5>BIBEE6GB><DG6,GD97DB-F78F-:;IDG7=FEFAB8A7D?+B>?F>F@75F7,6,,E6E7BF
@HS22_09330:8:2316:21273:82182#77
GGTGGCTGCACTTCACCGCCTTCGGGGCGCCGCTGGTGCCCGAGGTGAAGATCAGCATGAAAAGGTCTGCGAGATCCGCGGATCGAAAACGCACCTCGGT
+
9BB:@:D6,BDCCADD6DGAGFEH8H7A,BB-DBCEAEF7DF6EB-:H'D8CH@HE6>G?-:D:D87C@87D88?BF7BFE,;C>D,FFFCBDAC667@<
@HS22_09330:8:2316:21275:70978#77
TGGTCACCGCGGCAGGGCAACGGCATCGCTACGACACCCTGGTGCTGGCCACCGGCTCCTACGCATTCGTCTCGCCGGTGCCCGGCCACGACCTGCCCGC
+
8BA:DD:FF-FG8BEEB?6CB@G,DEDGEG,HB5FCAEE7C?=GIEGH7DCGD@DEEA,C-BEA88H-6CFD?@GC@,6,D?F>78D5F-CCA7DFE7,E
@HS22_09330:8:2316:21278:93966#77
ACCAGAAAACTCATCACGCCATCCCTTCCGCAGCTGGACGTGCCCGGGCCATCCCCTCCCGTGACCACAAACATCCGCTGGCTGAATACGCACAGCCCGA
+
9@@CEDCD@ECDEDE>FBE9GI@H8DFDE6HFEEB?7B?EE7JE@9EBF7CG?DHFEDGCGDEGHEDGFGDE,BFFGEGE6FCEED?FD7E?FE<FE-D4
@HS22_09330:8:2316:21278:97336#77
GGTGGTGTGGATCAACGATCCTTTGCCCTGGGTGATGGTGAGGTCACGGCTGAGGTAATCGGTAATCCGGATGGCCGCAGCACCGTCTGCACCTCTTCGG
+
9C=EEDDFGGFHDDEDGDEFGEGH8HCDEGHHBFEEAEFECFEGCHGDBGGEBGHDEEGF9DEIEGHCDCFEBHEFFHGE>FCE7BG=FFEEGIGFEGEC
@HS22_09330:8:2316:21280:71265#77
CTCGCGGTGCTGGCCGAGCACAAGACCGCGGTGCTCTCCCGAGCGCAACTCCTGGAATTGGTGTGGGGCTACGACTTCGCCGCCGCCACCAACGTGGTGG
+
7AAADD:?F-D?CBGD6BEB-7668?CAF,7HE5>7A?DCE7=7C?.=,GG9D989>AC?9:B:D@,8CB?A88AFB?GFI6F,>,?5D-CBF,4F>-@<
@HS22_09330:8:2316:21282:86263#77
GCGGCGGCCACAAGCGGCAGCCACAGCTCGAGCATCACCACCAGGTACTTGCCGCACGGCATGCCCATCAAGGCCCACACGTGCTCTAAAAGCGCCCTGG
+
06BA,D:68:8CCBAD6,6F9BE6GB'88B7-B5E778?>BF,E5-.+7G@9?C8@+>8?EAD:?,,8+CC58',EBA6BD6A'F8C5=C7?6ACB=DEC
@HS22_09330:8:2316:21283:13817#77
CAACACGGATTACGCGCCCGGGCTCAATGACACAGCGCCGGTCCCACGGGCCACAACGACAGCATGTCGGCGCCGAATTCGTGCACTAGTACACCCATAA
+
7ABAEDDADAFDCEEBBBBFGIAEDHFAE6D9EGE?EA7EDF6GIDGDBDCEHI?DDEGF>DEBFEEDG8DEG8FB@HFBE?FFEEEFGFE6EE<FC@@?
@HS22_09330:8:2316:21283:19945#77
CCAGCCCTACCGAAGCCATCAATGGCCGCCTGGATGCACTAAGCCGCAACGCCCTCGGATTGCCCGAGCTGCGGGCGCTAATGTGCGGCGATTCGCGGTT
+
9@BCB@-F8G>CAGEDG8FCG76EDB78EBDHE5CC7BGED'6G5?.=B@@ED98EDFC?CC.CDED8FDFE88ECBEGFCC5K7BD<DD,FF?CFEDE+
@HS22_09330:8:2316:21283:87768#77
GGCAACGAGGGTTGCCGGTTCCTCCACCGACCGTCCCGGCCCACTTCGACTGCCATTAGGCTGATCGAACGTGCCGGAAGCCGTCCAGGAAGCCGATCTG
+
8@=DE:D?FDCHCADFF8?FG7D?GBF8EBJ9EBBEI?D7D?,,BBGBB7CDB98F6CGCGFE:FCF8C8D,BC7BB76BCF5BACDFA7D,6AGB6G7F
@HS22_09330:8:2316:21286:89412#77
ACGATATCGGCGTCGGCCGCCGAGAAGTCCGGTGATTTCGCCAGGTCGGCGGCCGTGGTGCCGATCTCGATGTAGGCCTTGTCGGTGAACCGTTGAGACG
+
7@ACEDDFFE>CDEG>6DFFGI@HDHFCEFDEBG>BIF7>DGEGI?E=7GCG?D?@D>GFCFE:8EECDAD>D-FB,AGEGCFB>CC+AE>HFA<BB7E<
@HS22_09330:8:2316:21286:99840#77
CGTGCACCGGTTCGGGGGTGTCACCGGTGACGTGCTGGGCAGCGCGATCGAGCTGAGCACGACGGTCAGCGCCGGGACGCTTGCGGGCTTGTCCCGGATT
+
7@AE7DD6DB>D@5-',8GFGBDH?BFDE6J9=5E?,EDEFG=B59GB7D-GBIHEDA8EG:.--8?8GB7>D8,77?BF665>EC?+FDD,A?E,E',C
@HS22_09330:8:2316:21289:38137#77
ACCGCGCCCCGGATGGCAGGCATGTTGGAATACAACCATGGCTGCACTGCCGGCACCGGAGAAGCTCCTGCGCAGCGACTTTCCGGTGCTGTGGCCGGTG
+
767CBDCD,EFCCA:E6D6FGEEHDH7GC6DF6GCE=BA7H7EGF-DEF78?,-8@ED88'.BGEB7BCGCEBEE?7HBEGCDC7C7FF?C?DEBFBD'D
@HS22_09330:8:2316:21291:85251#77
TGGGTGGCTTCCGGTCACGTCGATGTCTTTCATGACCCGCTGGTCGAGTCGCTGATCACACATAAGCGCTACCGGGCCGACCATCTCATCGAGGCCTACG
+
7BAE7DCDFBCDEE:BBIBFGED@GH7GEFBFEDCCEED>EFBG+IED?DICII>FDCCDGFDCF8DCFGFAG@A?@EGFECDCEDGFADD?DEEF@DEF
@HS22_09330:8:2316:21293:22586#77
GCTGGCTAAAGAGCTTCACCGTGCGGACCGGCCCTCCGGCTTGGAATCCGTTCCACTTGATCTGGAGGTCGCAGAGGTAGAAGTTCTGGAAATCGCCGTA
+
0@AAE?D?FDCHAAEF??GFBIEEEHFCEGDFDEEBEFG>EGBEBBB+?GGC7@B9DHG?B:E:EG?G+BDED8EB@,GF>6F>DDDF=ECFEDGDE7@E
@HS22_09330:8:2316:21297:45939#77
TACACGGAGACCAAGCTGAACTCGGCATTCTCCTTCGGCGGGCCTAAGTGTCTAGTGAAGGTCATTCAGAAACTGTCGGGCTTGAGCATCAACCGGTTCA
+
9ABD7@A?DA8CE5GDB?EF(FECDC7G8?DH6FBBEA?EDF6EF?(D,@CGD@>-D7GDEI;:FECDFEFDG@?GBH676BF>FD75='D?AEH66@7C
@HS22_09330:8:2316:21302:76433#77
CCCAGTTGATCTCAGCACGATCCGGCGGAAGGCGGCCAAGCGGCTGGCCAAGGAGGTCAGCGCGGAGCTGTCCGCCCTGGCGATGGCCGATGCCGAATTC
+
7(AACDDF@DDCEEDDBDEFG,@HEC?8EBH9BB7E7FA>?FFGBGG6BG8CE(H9+HBE9BB-E8ECC-DD?@7F@CGE&?,C,CC+=DC?DEE',D@<
@HS22_09330:8:2316:21302:78686#77
TATTGGCCGCGGTCCCATCGGCGCCGTTGCCGTTCAGCGGACGCCCCCCCAGCCCCTGGGTGGGCGCGTTGATCAAACCCAGCACCCAGCAGACTACGCT
+
7-=C(DDBEDFD8AG+??6F97,D87C8?I79'5'77EGBB76E+-F',7@-7-ED>DAE'BB-E@7-CB7,8BEEFHB7,,;7EBC+AC,6=7C,<-B4
@HS22_09330:8:2316:21303:38694#77
CATCAGCCGTCGGTTCGACATAAGGAGCTTTTGACGTTGATGGCCGACGGTGTCCGAGTCGTCGGATCGTCGAGCATGGGCGCCCTGCGGGCGGCTGAGC
+
767A7D:DF:DDCEGDIF6FGFE@E7FAEGJH=B>EFA77?F=ECEDDE7@HD9?D>EBFF:EGDBD8?GFD?GA7@C?,CFEFAECFF-CB,IBBE@EE
@HS22_09330:8:2316:21304:19364#77
CTACCACCCAGGTGTTGGCCGCCGCCCAAGACGAGGTGTCAACGGCGATCGCCGCGCTGTTCGGCAGCCACGGCCAGCACTATCAAGCGATCAGCGCGCA
+
7B,C7DDADEFCCDAEFFB?GBAH8D?GE?HEEBCEAEFB?GEE<HFDHDIEDDHFDHGECF;AEEECFDFDDBECDHGEDFA'DD,F=CHFGAEDED@E
@HS22_09330:8:2316:21304:56718#77
TTCCGACATCGCTTGGAACCGTTGATGGAACGCGGTCTACTGGCCCGGTGCGGCATTACCGATCTCGAGTTCGGAGTCTCGGCGCGTTCCCGCGAGGACC
+
96AA,DC6EE@CEGAF68?FG7E68HFGEFD>BEB?BE?>DFE>FDED7GICB9CFDAGEGDEIEGEDFDCD?H?7G,C>DB5E,@75'E7'=7+F=7=4
@HS22_09330:8:2316:21306:67027#77
TTTCTCGATGGGCCGCACACCGATGAAGGCGGCGAGCGCCGCAATGTCCCGGTCTCGGTCGTAGCCGCGAAGTAGTTCGACGTAAGCGCAGTTTATCGAG
+
8-=:BDDBFGCHEDGDFF?FBGADGHFAEBDHFF>BIBKBFGEBFIGDEGGGEDCEHDGDGIEIFCHGGECDGBEFDHD7EFF7ADDFFCEHGDEFEGBE
@HS22_09330:8:2316:21306:94526#77
TTCTAAAAGCCGTTACCTGGCGGGCTTTGGATCGCGATCCACGCCATAGGTGTGGCTGTCTGGTCAGGTTTGACCGGCGCCATGATGTCGTTTCACAGCG
+
7>A@7DDFDGDCEGAFIEEFGBDEGHFGEGDFBGCEBAF>EFGBCBB6ED@C?GHDEAGFE:DA?GEGDDFDCHE7GBGEG6EC78C?=D7FGEEFEC7F
@HS22_09330:8:2316:21309:31838#77
NNNTAGTCGCCGACCACGCCGGCTACATGTCCAACTATTTCCGCTGGTTCGGCAGCCCGGAGGATCCCTTCGGCTGGTATTACAACCTGCTGGCGCTGAT
+
!!!-7DD6,-F?8A:D6DGC=D@E8HFCFBD9=DCCAEGCDABBBEGB7@CCHG?9EHBF9DBAD@DBFDAD?HE?DE+>EF,CADC+=7>CD7<FED,<
@HS22_09330:8:2316:21310:32094#77
NNNCATAAGGCCCATGCCGTCGGGTAGGCCGCCGTGGTGATCAAACTACCGAACAGTGGGGGTCCGGCGGCCGCCATCAGCCGCTGCGTAGTGTTCTGGA
+
!!!A,D:BD->DD5GDIIEF=IE68E?DEGHFDDEEI?E>CEEGCEGD7GGE7DDBEA8FBI;IE8D8+DFDGBE7GEBFE65CEBGFFCDCDEDFEG7'
@HS22_09330:8:2316:21311:62456#77
NNNCAACCGGCTCAAGACTGCGACCGGGTTGACCTTGCCACCGACCTTGATCTTTGACTACCCCACGGCCCCGGAGTTGGCCGAACACTTCGACATCCAG
+
!!!:,DC?8(8H@5AF?DF9B@6EDHFGCFHE6BEEA87>CFEJFGGECDGEH9DDFD=F9BE:8E7868'>,8'CG7G>6?A>,,,F'776,E+>@7,<
@HS22_09330:8:2316:21314:54701#77
NNNNCGGCTATCGCCGAGCTTACCGGCCGGCGCACCGGCGCGGACCAGCGGGCCGACTGGGCGTGTGACTTCTGGGACTGCGCGGCCGCGGAGGTGGCTG
+
!!!!CDCF8:DCDGGDFEGF-EDHGH?GGFDHEFBEDIAFBFEGFDGEEGGG7GHEFHGFE.EDECE8FGFDG@GFBHCFCFFCFDGF=GC,FE+>E@DF
@HS22_09330:8:2316:21315:56524#77
NNNNTCCCTTTTCTCAACATTGCCGAAGACCACCTGTATGGGGAGGCAACGATGGCCGAATCAACCGGGCCCAAGCCCCGGGGGCGGCCCGCGGGGGGGG
+
!!!!7?-?(-,?EA?6BF?F9EE68,,DCBB9FB7?,,,,C,''+-D''78-7D>D+,8''(.-E#7-6'C,,-7,7,'E66',7,,557C,6,HFE'&4

**Comment by Phelimb** [comment] 2014-10-16 16:21
Also here : 
https://www.dropbox.com/s/1qktrq1c00zojjv/tail_fq.fastq?dl=0 
incase git's markdown parsing has done anything funny.

**Comment by kvarq** [comment] 2014-10-17 13:09
I can't reproduce the error. If you provide me with one complete file that produces the error & the exact configuration you are using (version, command line parameters) I will check it out.

**Comment by Phelimb** [comment] 2014-10-17 13:55
This was the commandline I envoked: 

python ~/tools/kvarq-master/kvarq/cli.py  -t ~/tools/kvarq-master/testsuites/MTBC/ scan -p fastqs/C00014613.fastq.gz kvarq/C00014613.json 

Full file can be found here: 
https://www.dropbox.com/s/z27krq9kybncjkc/C00014613.fastq.gz?dl=0

**Comment by Phelimb** [comment] 2014-10-17 13:57
Since I downloaded this file locally I tried running it through the kvarq.app (on mac) and I got a different error: 

[2014-08-07 12:49:18,092] -INFO- settings.pyc:118(load_testsuites) :: loaded testsuite "resistance" 1.0
[2014-10-17 14:50:37,215] -INFO- settings.pyc:118(load_testsuites) :: loaded testsuite "resistance" 1.0
[2014-10-17 14:53:11,407] -INFO- fastq.pyc:146(**init**) :: gzipped fastq : readlength=? records_approx=? dQ=0 variants=['Sanger']
[2014-10-17 14:53:13,136] -INFO- simple.pyc:183(startstop) :: start scanning /Users/phelimb/Dropbox/Temp/C00014613.fastq.gz (373 MB)
[2014-10-17 14:53:13,237] -ERROR- simple.pyc:241(update) :: could not scan /Users/phelimb/Dropbox/Temp/C00014613.fastq.gz : buf_size < fastq->buf_size !

**Comment by kvarq** [comment] 2014-10-18 13:05
the bug at the origin of the error message `could not scan file : record must start with '@' (and not 'F')` is fixed as of commit ab02ab5

I was not able to reproduce the error message `buf_size < fastq->buf_size !` – please open a new issue if this problem persists

**Closed as completed by kvarq** 2014-10-18 13:05 UTC
